看到源码默认的图片解码格式为ARGB_8888,和Picasso的默认格式相同了（貌似以前是RGB565）这个会多占内存了但是速度却快了，这需要牺牲空间换来换取更多的时间。

Glide.get(context)这里实际上是通过单例模式初始化Glide对象并赋值

builder.build内部通过构建者模式出创建实例

这个方法内部主要用于创建一个Fragment主要用来实现的Glide对Activity生命周期的感知作用（真是看了源码觉得fragment 还可以这样用）最终返回RequestManager。

RecyclerView使用四级缓存来进行视图的复用，缓存的逻辑主要集中在内部类Recycler中

mAttachedScrap--用于快速重用屏幕上可见的列表项ItemView，而不需要重新createView和bindViewmCachedViews--缓存离开屏幕的ItemView，目的是让即将进入屏幕的ItemView重用，使用这个缓存时不需要重新createView和bindViewmViewCacheExtension--不直接使用，用户定制的缓存mRecyclerPool--也是缓存离开屏幕的ItemView，但需要重新bindView

自定义缓存可以让用户自行设置缓存的策略
 
RecyclerView四级缓存：mAttachedScrap，mCachedViews，mViewCacheExtension，mRecyclerPoolmCachedViews 优先级高于 RecyclerViewPool，回收时，最新的 ViewHolder 都是往 mCachedViews 里放，如果它满了，那就移出一个扔到 ViewPool 里好空出位置来缓存最新的 ViewHolder。mAttachedScrap，mCachedViews取出来的均不需要重新bindView，而mRecyclerPool取出来的则需要进行bindView
